version: '3.9'

services:
  employee_mongo:
    image: mongo:6
    container_name: employee_mongo
    restart: unless-stopped
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db

  employee_backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: employee_backend
    restart: unless-stopped
    ports:
      - "3338:3338"
    env_file:
      - .env
    depends_on:
      - employee_mongo

  employee_frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: employee_frontend
    restart: unless-stopped
    ports:
      - "5005:5005"
    depends_on:
      - employee_backend

volumes:
  mongo_data:

